import pytest


# test_interaction_hh_ru
@pytest.fixture()
def test_hh_api():
    return [
        {
            "id": "116876598",
            "premium": False,
            "name": "Стажер Python Developer",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {
                "id": "2759",
                "name": "Ташкент",
                "url": "https://api.hh.ru/areas/2759",
            },
            "salary": None,
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Ташкент",
                "street": "улица Ифтихор",
                "building": "1/11",
                "lat": 41.348373,
                "lng": 69.285962,
                "description": None,
                "raw": "Ташкент, улица Ифтихор, 1/11",
                "metro": None,
                "metro_stations": [],
                "id": "16911351",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-02-07T09:15:58+0300",
            "created_at": "2025-02-07T09:15:58+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=116876598",
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/116876598?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/116876598",
            "relations": [],
            "employer": {
                "id": "11559047",
                "name": "DEEPEN",
                "url": "https://api.hh.ru/employers/11559047",
                "alternate_url": "https://hh.ru/employer/11559047",
                "logo_urls": None,
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=11559047",
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Hard Skills. - <highlighttext>Python</highlighttext> "
                               "Expertise: Proficient in "
                               "<highlighttext>Python</highlighttext> programming, with a strong "
                               "understanding of its "
                               "libraries and frameworks such as Django...",
                "responsibility": "Software Development: Design, develop, and maintain high-quality "
                                  "<highlighttext>Python</highlighttext> applications. - Code Review: "
                                  "Conduct thorough "
                                  "code reviews to ensure code quality...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [],
            "working_hours": [{"id": "HOURS_8", "name": "8 часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}],
            "night_shifts": False,
            "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between3And6", "name": "От 3 до 6 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": True,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "116796595",
            "premium": False,
            "name": "Аналитик данных/Продуктовый аналитик (Python)",
            "department": {"id": "yandex-1740-yandex", "name": "Яндекс"},
            "has_test": False,
            "response_letter_required": False,
            "area": {
                "id": "113",
                "name": "Россия",
                "url": "https://api.hh.ru/areas/113",
            },
            "salary": None,
            "type": {"id": "direct", "name": "Рекламная"},
            "address": None,
            "response_url": "https://yandex.ru/project/events/wo-analytics-0325?"
                            "utm_source=headhunter&utm_medium=direct_response&utm_campaign="
                            "wo_analytics_0325",
            "sort_point_distance": None,
            "published_at": "2025-02-05T12:49:01+0300",
            "created_at": "2025-02-05T12:49:01+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=116796595",
            "video_vacancy": {
                "video_url": "https://storage.yandexcloud.net/hhdisk-video-vacancy-prod/78d63845-8d79-"
                             "4e87-b787-d17edbd95f30_original.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-"
                             "Amz-Credential=YCAJEGF2cq2Ivt4zBoWonIaIu%2F20250209%2Fus-east-1%2Fs3%2"
                             "Faws4_request&X-Amz-Date=20250209T053754Z&X-Amz-Expires=86400&X-Amz-"
                             "SignedHeaders=host&X-Amz-Signature="
                             "426ac26f6dca75c32fba104de040ee61b7d49afa3d09e7b767347283c3ca08a0",
                "cover_picture": {
                    "resized_path": "https://img.hhcdn.ru/branding-pictures/3150337.jpeg",
                    "resized_width": 1182,
                    "resized_height": 666,
                },
                "snippet_video_url": None,
                "snippet_picture_url": None,
            },
            "show_logo_in_search": None,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/116796595?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/116796595",
            "relations": [],
            "employer": {
                "id": "1740",
                "name": "Яндекс",
                "url": "https://api.hh.ru/employers/1740",
                "alternate_url": "https://hh.ru/employer/1740",
                "logo_urls": {
                    "90": "https://img.hhcdn.ru/employer-logo/3790847.png",
                    "240": "https://img.hhcdn.ru/employer-logo/3790848.png",
                    "original": "https://img.hhcdn.ru/employer-logo-original/837491.png",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=1740",
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Ищем аналитиков с опытом на <highlighttext>Python</highlighttext> от 2 лет.",
                "responsibility": None,
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "HYBRID", "name": "Гибрид"}],
            "working_hours": [{"id": "HOURS_8", "name": "8 часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}],
            "night_shifts": False,
            "professional_roles": [{"id": "10", "name": "Аналитик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": False,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
    ]


# test_extra_functions
@pytest.fixture()
def test_functions():
    return [
        {
            "id": "116880559",
            "premium": False,
            "name": "Стажер Data Scientist",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {
                "id": "4",
                "name": "Новосибирск",
                "url": "https://api.hh.ru/areas/4",
            },
            "salary": 20000,
            "type": {"id": "open", "name": "Открытая"},
            "address": None,
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-02-07T09:42:27+0300",
            "created_at": "2025-02-07T09:42:27+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=116880559",
            "show_logo_in_search": None,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/116880559?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/116880559",
            "relations": [],
            "employer": {
                "id": "6028086",
                "name": "Data Acquisition",
                "url": "https://api.hh.ru/employers/6028086",
                "alternate_url": "https://hh.ru/employer/6028086",
                "logo_urls": {
                    "90": "https://img.hhcdn.ru/employer-logo/6536037.png",
                    "240": "https://img.hhcdn.ru/employer-logo/6536038.png",
                    "original": "https://img.hhcdn.ru/employer-logo-original/1228899.png",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=6028086",
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Пунктуальность, систематичность, ответственное отношение к дедлайнам. . "
                               "Уверенное владения <highlighttext>Python</highlighttext> для ML "
                               "(преимущественно nlp и cv). . Опыт реализации и применения моделей...",
                "responsibility": "Реализация проектов из сфер CV, NLP, построение предиктивных моделей "
                                  "и других задач из сферы. Работа с подготовкой и аннотацией данных...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": True,
            "fly_in_fly_out_duration": [],
            "work_format": [],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}],
            "night_shifts": False,
            "professional_roles": [{"id": "165", "name": "Дата-сайентист"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "noExperience", "name": "Нет опыта"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": True,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
            "currency": "RUR",
        },
        {
            "id": "116796595",
            "premium": False,
            "name": "Аналитик данных/Продуктовый аналитик (Python)",
            "department": {"id": "yandex-1740-yandex", "name": "Яндекс"},
            "has_test": False,
            "response_letter_required": False,
            "area": {
                "id": "113",
                "name": "Россия",
                "url": "https://api.hh.ru/areas/113",
            },
            "salary": 0,
            "type": {"id": "direct", "name": "Рекламная"},
            "address": None,
            "response_url": "https://yandex.ru/project/events/wo-analytics-0325?utm_source="
                            "headhunter&utm_medium=direct_response&utm_campaign=wo_analytics_0325",
            "sort_point_distance": None,
            "published_at": "2025-02-05T12:49:01+0300",
            "created_at": "2025-02-05T12:49:01+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=116796595",
            "video_vacancy": {
                "video_url": "https://storage.yandexcloud.net/hhdisk-video-vacancy-prod/78d63845-8d79"
                             "-4e87-b787-d17edbd95f30_original.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-"
                             "Amz-Credential=YCAJEGF2cq2Ivt4zBoWonIaIu%2F20250209%2Fus-east-1%2Fs3%2"
                             "Faws4_request&X-Amz-Date=20250209T091836Z&X-Amz-Expires=86400&X-Amz-"
                             "SignedHeaders=host&X-Amz-Signature=076a679f943c8f8ac6e4afb23d37d931b79"
                             "e522411ccee1dbd645f31cdf26575",
                "cover_picture": {
                    "resized_path": "https://img.hhcdn.ru/branding-pictures/3150337.jpeg",
                    "resized_width": 1182,
                    "resized_height": 666,
                },
                "snippet_video_url": None,
                "snippet_picture_url": None,
            },
            "show_logo_in_search": None,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/116796595?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/116796595",
            "relations": [],
            "employer": {
                "id": "1740",
                "name": "Яндекс",
                "url": "https://api.hh.ru/employers/1740",
                "alternate_url": "https://hh.ru/employer/1740",
                "logo_urls": {
                    "90": "https://img.hhcdn.ru/employer-logo/3790847.png",
                    "240": "https://img.hhcdn.ru/employer-logo/3790848.png",
                    "original": "https://img.hhcdn.ru/employer-logo-original/837491.png",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=1740",
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Ищем аналитиков с опытом на <highlighttext>Python</highlighttext> от 2 лет.",
                "responsibility": None,
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "HYBRID", "name": "Гибрид"}],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}],
            "night_shifts": False,
            "professional_roles": [{"id": "10", "name": "Аналитик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": False,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "116792570",
            "premium": False,
            "name": "Junior Developer (стажер)",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "1", "name": "Москва", "url": "https://api.hh.ru/areas/1"},
            "salary": 70000,
            "type": {"id": "open", "name": "Открытая"},
            "address": None,
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-02-05T11:44:48+0300",
            "created_at": "2025-02-05T11:44:48+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=116792570",
            "show_logo_in_search": None,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/116792570?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/116792570",
            "relations": [],
            "employer": {
                "id": "11254763",
                "name": "NEXTLINE Лаборатория рекламы",
                "url": "https://api.hh.ru/employers/11254763",
                "alternate_url": "https://hh.ru/employer/11254763",
                "logo_urls": {
                    "90": "https://img.hhcdn.ru/employer-logo/6830758.png",
                    "original": "https://img.hhcdn.ru/employer-logo-original/1302624.png",
                    "240": "https://img.hhcdn.ru/employer-logo/6830759.png",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=11254763",
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Базовые знания фронтенд-технологий: HTML, CSS, JavaScript."
                               "Опыт работы на одном из серверных языков: PHP, Python."
                               "Понимание основ реляционных (MySQL, PostgreSQL) баз...",
                "responsibility": "Участие в разработке программного обеспечения и "
                                  "административной части проекта. Участие в разработке программного "
                                  "обеспечения и административной части проекта. ",
            },
            "contacts": None,
            "schedule": {"id": "flexible", "name": "Гибкий график"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [
                {"id": "ON_SITE", "name": "На\xa0месте работодателя"},
                {"id": "HYBRID", "name": "Гибрид"},
            ],
            "working_hours": [{"id": "FLEXIBLE", "name": "По\xa0договорённости"}],
            "work_schedule_by_days": [{"id": "OTHER", "name": "Другое"}],
            "night_shifts": False,
            "professional_roles": [{"id": "40", "name": "Другое"}],
            "accept_incomplete_resumes": True,
            "experience": {"id": "noExperience", "name": "Нет опыта"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": False,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
            "currency": "RUR",
        },
    ]
